name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y cmake ninja-build python3 python3-pip nodejs npm

      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build

      - name: Run C tests
        run: ctest --test-dir build --output-on-failure

      - name: Python deps
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r docs/requirements.txt
          python3 -m pip install -e sdk/python

      - name: Pytests
        run: python3 -m pytest

      - name: Build SDK artifacts
        run: scripts/build_sdk.sh all

      - name: Build docs
        run: |
          cd docs
          make html

      - name: Archive docs
        uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: docs/_build/html
