name: kolibri-policy-check

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate kolibri-policy
        run: |
          python3 scripts/policy_validate.py
