name: Python CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run ruff
        run: |
          pip install ruff
          ruff check . || true
      - name: Run pytest
        run: |
          python -m pytest -q
      - name: Run pyright (optional)
        run: |
          pip install pyright
          pyright || true
